apiVersion: apps/v1
kind: Deployment
metadata:
  name: endo-client
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: endo-client
  template:
    metadata:
      labels:
        app: endo-client
    spec:
      containers:
        - name: endo-client
          image: vagtsop/endo-endo-client-container:latest
          volumeMounts:
          - name: endo-client-configmap
            mountPath: /etc/nginx
      volumes:
      - name: endo-client-configmap
        configMap:
          name: endo-client-configmap     
      imagePullSecrets:
        - name: dbsecret  