apiVersion: v1
kind: Service
metadata:
  name: endo-client
spec:
  type: LoadBalancer
  selector:
    app: endo-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443  