export enum Field {
  INSTRUMENT_NAME = 'INSTRUMENT_NAME',
  INSTRUMENT_REF = 'INSTRUMENT_REF',
  INSTRUMENT_LOT = 'INSTRUMENT_LOT',
  INSTRUMENT_MANUFACTURER = 'INSTRUMENT_MANUFACTURER',
  INSTRUMENT_PURCHASE_DATE = 'INSTRUMENT_PURCHASE_DATE',
  INSTRUMENT_SERIES_CODE = 'INSTRUMENT_SERIES_CODE',
  ID = 'ID',
  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  USERNAME = 'USERNAME',
  EMAIL = 'EMAIL',
  ROLE = 'ROLE',
  STATUS = 'STATUS',
  LOCKED = 'LOCKED'
}
